spring.application.name=primeiro
# Mundando a porta
server.port=8081
# Configuração do banco de dados
spring.datasource.url=jdbc:h2:./data/mydb
spring.datasource.ClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=
# Habilitar o H2-Console : http://localhost:8080/h2-console
spring.h2.console.enable=true
spring.h2.console.path=/h2-console
# Configuração do hibernate
spring.jpa.database.plataform=org.hibernate.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true